-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 13:21:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_sagres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_sagres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_sagres` DEFAULT CHARACTER SET utf8 ;
USE `projeto_sagres` ;

-- -----------------------------------------------------
-- Table `projeto_sagres`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Endereco` (
  `idEndereco` INT NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `complemento` VARCHAR(30) NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Curso` (
  `idCurso` INT NOT NULL,
  `nomeCurso` VARCHAR(30) NOT NULL,
  `tipoCurso` VARCHAR(10) NOT NULL,
  `quantidadeSemestres` INT NOT NULL,
  `cargaHorariaCurso` INT NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(50) NOT NULL,
  `numMatricula` INT NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `ufRg` VARCHAR(2) NOT NULL,
  `orgaoExpeditorRg` VARCHAR(45) NOT NULL,
  `dataExpedicaoRg` VARCHAR(10) NOT NULL,
  `curso` VARCHAR(30) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `dataNascimento` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_Aluno_Endereco_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Endereco`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `projeto_sagres`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `projeto_sagres`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Professor` (
  `nomeProfessor` VARCHAR(50) NOT NULL,
  `areaProfessor` VARCHAR(30) NOT NULL,
  `numMatricula` INT NOT NULL,
  `cargaHoraria` INT NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `id` INT NOT NULL,
  INDEX `fk_Professor_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Professor_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `projeto_sagres`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Classe` (
  `idClasse` INT NOT NULL,
  `diaHora` VARCHAR(30) NOT NULL,
  `periodoLetivo` CHAR(5) NOT NULL,
  PRIMARY KEY (`idClasse`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nomeDisciplina` VARCHAR(50) NOT NULL,
  `areaDisciplina` VARCHAR(30) NOT NULL,
  `semestre` INT NOT NULL,
  `teorica` TINYINT NOT NULL,
  `pratica` TINYINT NOT NULL,
  `estagio` TINYINT NOT NULL,
  `cargaHoraria` INT NOT NULL,
  `ePreRequisito` TINYINT NOT NULL,
  `Classe_idClasse` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX `fk_Disciplina_Classe1_idx` (`Classe_idClasse` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_Classe1`
    FOREIGN KEY (`Classe_idClasse`)
    REFERENCES `projeto_sagres`.`Classe` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Aluno_cursou_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Aluno_cursou_Disciplina` (
  `Aluno_idAluno` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Disciplina_idDisciplina`),
  INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Disciplina_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `projeto_sagres`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `projeto_sagres`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Disciplina_pertence_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Disciplina_pertence_Curso` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Curso_idCurso`),
  INDEX `fk_Disciplina_has_Curso_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Curso_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Curso_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `projeto_sagres`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Curso_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `projeto_sagres`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Aluno_estuda_Classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Aluno_estuda_Classe` (
  `Aluno_idAluno` INT NOT NULL,
  `Classe_idClasse` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Classe_idClasse`),
  INDEX `fk_Aluno_has_Classe_Classe1_idx` (`Classe_idClasse` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Classe_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Classe_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `projeto_sagres`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Classe_Classe1`
    FOREIGN KEY (`Classe_idClasse`)
    REFERENCES `projeto_sagres`.`Classe` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_sagres`.`Professor_da_aulas_Classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sagres`.`Professor_da_aulas_Classe` (
  `Professor_id` INT NOT NULL,
  `Classe_idClasse` INT NOT NULL,
  PRIMARY KEY (`Professor_id`, `Classe_idClasse`),
  INDEX `fk_Professor_has_Classe_Classe1_idx` (`Classe_idClasse` ASC) VISIBLE,
  INDEX `fk_Professor_has_Classe_Professor1_idx` (`Professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Classe_Professor1`
    FOREIGN KEY (`Professor_id`)
    REFERENCES `projeto_sagres`.`Professor` (`numMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Classe_Classe1`
    FOREIGN KEY (`Classe_idClasse`)
    REFERENCES `projeto_sagres`.`Classe` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
